version: '3'

services:
    mariadb:
        build: ./requirements/mariadb 
        image: mariadb_image
        container_name : mariadb
        restart: unless-stopped
        ports:
            - "3306:3306"
        env_file:
            - .env
        networks:
            - wordpress
        volumes:
            - database:/var/lib/mysql

    nginx:
        build: ./requirements/nginx
        image: nginx_image
        container_name : nginx
        depends_on:
            - wordpress
        restart: unless-stopped
        ports:
            - "443:443"
        volumes:
            - 'wordpress:/var/www/html/'
        networks:
            - wordpress

    wordpress:
        build: ./requirements/wordpress
        image: wordpress_image
        container_name : wordpress
        depends_on:
            - mariadb
        restart: unless-stopped
        ports:
            - "9000:9000"
        env_file:
            - .env
        volumes:
            - 'wordpress:/var/www/html/'
        networks:
            - wordpress

networks:
  wordpress:

volumes:
    wordpress:
        driver: "local"
        driver_opts:
            o: bind
            type: ext4
            device: /home/mamali/data/wp
    database: 
            driver: local
            driver_opts:
                    type: none
                    device: /home/mamali/data/db
                    o: bind